package tentech.healthcheck.enums;

public enum Services {
    ALLERGOLOGY,
    ANESTHESIOLOGY,
    VACCINATION,
    GYNECOLOGY,
    CARDIOLOGY,
    NEUROSURGERY,
    ORTHOPEDICS,
    OPHTHALMOLOGY,
    PSYCHOTHERAPY,
    RHEUMATOLOGY,
    UROLOGY,
    ENDOCRINOLOGY,
    GASTROENTEROLOGY,
    DERMATOLOGY,
    NEUROLOGY,
    ONCOLOGY,
    OTOLARYNGOLOGY, // ЛОР
    PROTOLOGY,
    PULMONOLOGY,
    THERAPY,
    PHLEBOLOGY,
    PHYSIOTHERAPY
}
